# Generated by Django 5.2.5 on 2025-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tournament_wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
