# Generated by Django 5.2.5 on 2025-08-19 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_song_tournament_wins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-tournament_wins'], name='song_tournament_wins_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-total_wins'], name='song_total_wins_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-total_picks'], name='song_total_picks_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['total_picks'], name='song_total_picks_gt_idx'),
        ),
        migrations.AddIndex(
            model_name='votingsession',
            index=models.Index(fields=['status'], name='voting_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='votingsession',
            index=models.Index(fields=['user'], name='voting_session_user_idx'),
        ),
        migrations.AddIndex(
            model_name='votingsession',
            index=models.Index(fields=['session_key'], name='voting_session_key_idx'),
        ),
        migrations.AddIndex(
            model_name='votingsession',
            index=models.Index(fields=['-created_at'], name='voting_session_created_idx'),
        ),
    ]
