# Generated by Django 5.2.5 on 2025-08-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="artist",
            new_name="original_song",
        ),
    ]
