version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DEBUG=True
      - OSU_CLIENT_ID=${OSU_CLIENT_ID:-your_client_id_here}
      - OSU_CLIENT_SECRET=${OSU_CLIENT_SECRET:-your_client_secret_here}
      - OSU_REDIRECT_URI=http://localhost:8000/auth/callback/
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=hello_beomsan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: