# fly.toml configuration for Django deployment

app = 'hello-beomsan'
primary_region = 'nrt'

[build]

[deploy]
  release_command = 'python manage.py migrate && python manage.py promote_admin && python manage.py collectstatic --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1