# fly.toml app configuration file generated for Django app
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-beomsan'
primary_region = 'nrt'
console_command = '/code/manage.py shell'

[build]
  dockerfile = "Dockerfile"

# LiteFS handles migrations in litefs.yml exec section
# [deploy]
#   release_command = '/bin/sh -c "python manage.py collectstatic --noinput"'

[env]
  PORT = '8000'
  PRIMARY_REGION = 'nrt'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'litefs'
  destination = '/var/lib/litefs'

[[statics]]
  guest_path = '/code/staticfiles'
  url_prefix = '/static/'