# Generated by Django 5.2.5 on 2025-08-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_add_performance_indexes'),
    ]

    operations = [
        # Add indexes to optimize fibonacci scoring queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS match_winner_round_idx ON matches (winner_id, round_number);",
            reverse_sql="DROP INDEX IF EXISTS match_winner_round_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS match_round_number_idx ON matches (round_number);", 
            reverse_sql="DROP INDEX IF EXISTS match_round_number_idx;"
        ),
    ]
